/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.summercoding.bank.ui;

import com.summercoding.bank.controlleur.Controlleur;
import com.summercoding.bank.entities.Admin;
import com.summercoding.bank.entities.Utilisateur;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author ETHAN BOY
 */
public class JFrameHome extends javax.swing.JFrame {
    
    Controlleur controlleur = new Controlleur();
    String quelModel;
    private String quelMenu;
   
  

    /**
     * Creates new form JFrameHome
     */
    public JFrameHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuAdmin = new javax.swing.JMenu();
        createAdmin = new javax.swing.JMenuItem();
        listAdmin = new javax.swing.JMenuItem();
        MenuUtilisateur = new javax.swing.JMenu();
        createUser = new javax.swing.JMenuItem();
        listUser = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        createCompte = new javax.swing.JMenuItem();
        listCompte = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenuItem1.setText("jMenuItem1");

        jMenu2.setText("File");
        jMenuBar2.add(jMenu2);

        jMenu9.setText("Edit");
        jMenuBar2.add(jMenu9);

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
        );

        MenuAdmin.setText("Admin");

        createAdmin.setText("create");
        createAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAdminActionPerformed(evt);
            }
        });
        MenuAdmin.add(createAdmin);

        listAdmin.setText("list");
        listAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listAdminActionPerformed(evt);
            }
        });
        MenuAdmin.add(listAdmin);

        jMenuBar1.add(MenuAdmin);

        MenuUtilisateur.setText("Utilisateur");
        MenuUtilisateur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuUtilisateurActionPerformed(evt);
            }
        });

        createUser.setText("create");
        createUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createUserActionPerformed(evt);
            }
        });
        MenuUtilisateur.add(createUser);

        listUser.setText("list");
        listUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listUserActionPerformed(evt);
            }
        });
        MenuUtilisateur.add(listUser);

        jMenuBar1.add(MenuUtilisateur);

        jMenu10.setText("Compte");

        createCompte.setText("create");
        createCompte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createCompteActionPerformed(evt);
            }
        });
        jMenu10.add(createCompte);

        listCompte.setText("list");
        jMenu10.add(listCompte);

        jMenuBar1.add(jMenu10);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAdminActionPerformed
        new JFramesaveAdmin("add",0,this).setVisible(true);
    }//GEN-LAST:event_createAdminActionPerformed

    private void listAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listAdminActionPerformed
        quelMenu = "admin";
        try {
            // TODO add your handling code here:
            DefaultTableModel model = new DefaultTableModel();
            
            model.addColumn("Id");
            model.addColumn("Nom");
            model.addColumn("Login");
            
            List<Admin> listAdmin = controlleur.routeVerlistAllAdmin();
            for(Admin ad :listAdmin) 
                model.addRow(new String[]{ad.getIdadmin()+"",ad.getNom(), ad.getLogin()});
            
            table.setModel(model);
                
        } catch (SQLException ex) {
            Logger.getLogger(JFrameHome.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_listAdminActionPerformed

    private void createUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createUserActionPerformed
        // TODO add your handling code here:
        new JFramesaveUtilisateur().setVisible(true);
    }//GEN-LAST:event_createUserActionPerformed

    private void createCompteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createCompteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createCompteActionPerformed

    private void MenuUtilisateurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuUtilisateurActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_MenuUtilisateurActionPerformed

    private void listUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listUserActionPerformed
           try {
            // TODO add your handling code here:
            DefaultTableModel model = new DefaultTableModel();
            
            model.addColumn("Id");
            model.addColumn("Nom");
            model.addColumn("Login");
            model.addColumn("Prenom");
            model.addColumn("Genre");
            model.addColumn("Datenaiss");
            model.addColumn("Idadmin");
            List<Utilisateur> listUtilisateur = controlleur.routeVerlistAllUtilisateur();
            for(Utilisateur ad :listUtilisateur) 
                model.addRow(new String[]{ad.getIduser()+"",ad.getNom(), ad.getLogin(),ad.getPrenom(),ad.getGenre(),ad.getDatenaiss()+"",ad.getIdadmin()+""});
            
            table.setModel(model);
                
        } catch (SQLException ex) {
            Logger.getLogger(JFrameHome.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_listUserActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        int numeroLigne = table.getSelectedRow();
        TableModel model = table.getModel();
        
        if(quelMenu.equals("admin")){
        
        String id = model.getValueAt(numeroLigne, 0).toString();
        int idadmin = Integer.parseInt(id);
        
        JFramesaveAdmin jFramesaveAdmin = 
                
                new JFramesaveAdmin("update", idadmin, this);
        
        jFramesaveAdmin.setVisible(true);
    }
    }//GEN-LAST:event_tableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameHome().setVisible(true);
            }
        });
    }

    public JTable getTable() {
        return table;
    }

    public void setTable(JTable table) {
        this.table = table;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuAdmin;
    private javax.swing.JMenu MenuUtilisateur;
    private javax.swing.JMenuItem createAdmin;
    private javax.swing.JMenuItem createCompte;
    private javax.swing.JMenuItem createUser;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem listAdmin;
    private javax.swing.JMenuItem listCompte;
    private javax.swing.JMenuItem listUser;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
